### ISSUE TITLE
Windows support in `@exemplar\storybook-react`

### ISSUE THREAD

**Issue by msluther** [godaddy/exemplar#19]
There's a windows bug that causes these `require.context`s to fail: https://github.com/godaddy/exemplar/blob/7f6b96b16130b9e5bdce34f62c97b9fa6a523e58/packages/exemplar-storybook-react/load-examples.js#L39

When running this I saw full windows paths showing up but without the backslashes, e.g. `C:FooBarBazFizzBuzz` instead of `C:\Foo\Bar\Baz\Fizz\Buzz`.  I wasn't able to debug at the time to get much more information.  This was on a fairly standard `hello-world`-style react component without anything really special.

**Comment by rxmarbles** [comment]
repo is archived as well as package is deprecated
